Background:     #0d1117
Highlight:      #ff7b72
Lowlight:       #65312d
Text:           #f0883e
Data:           #d5ff80
Black:          #000000
EditText:       #a5d6ff
EditBG:         #0a0c06
EditBGlow:      #14180c
EditBGhigh:     #293118
Brighttext:     #f5f5f5
SelectedBGLow:  #180b0a
SelectedBGHigh: #65312d
LCDHigh:        #FF0000
LCDMid:         #A00000
LCDLow:         #600000
CursorRowHigh:  #646464
CursorRowLow:   #303030