Background:     #0c0000
Highlight:      #87ceeb
Lowlight:       #2e4751
Text:           #00b200
Data:           #cc66cc
Black:          #000000
EditText:       #ffff00
EditBG:         #000000
EditBGlow:      #650000
EditBGhigh:     #cc0000
Brighttext:     #cfcfcf
SelectedBGLow:  #180018
SelectedBGHigh: #650065
LCDHigh:        #FF0000
LCDMid:         #A00000
LCDLow:         #600000
CursorRowHigh:  #767676
CursorRowLow:   #464646