Background:     #1a1724
Highlight:      #ff9ab3
Lowlight:       #3e3958
Text:           #78dce8
Data:           #a9dc76
Black:          #000000
EditText:       #fc9867
EditBG:         #08070b
EditBGlow:      #0d191b
EditBGhigh:     #284a4e
Brighttext:     #cfcfcf
SelectedBGLow:  #181409
SelectedBGHigh: #655628
LCDHigh:        #FF0000
LCDMid:         #A00000
LCDLow:         #600000
CursorRowHigh:  #505050
CursorRowLow:   #202020