Background:     #1d2331
Highlight:      #9c85b2
Lowlight:       #2b2531
Text:           #d5ff80
Data:           #73d0ff
Black:          #000000
EditText:       #ffad66
EditBG:         #05090c
EditBGlow:      #0a1318
EditBGhigh:     #2d5265
Brighttext:     #cfcfcf
SelectedBGLow:  #0e0b05
SelectedBGHigh: #65532d
LCDHigh:        #FF0000
LCDMid:         #A00000
LCDLow:         #600000
CursorRowHigh:  #767676
CursorRowLow:   #464646